projectsite/projectsite/urls.py
from django.contrib import admin
from django.urls import path
from Order.views import (
    BrandListView, ShoeListView, ShoeDetailView,
    CommentCreateView, OrderListView, OrderDetailView,
    CustomerListView, home
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('brand/', BrandListView.as_view(), name='brand-list'),
    path('shoe/', ShoeListView.as_view(), name='shoe-list'),
    path('shoe/<int:pk>/', ShoeDetailView.as_view(), name='shoe-detail'),
    path('shoe/<int:product_id>/review/', CommentCreateView.as_view(), name='comment-create'),
    path('orders/', OrderListView.as_view(), name='order-list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('customers/', CustomerListView.as_view(), name='customer-list'),
    

]

projectsite/Order/models.py
from django.db import models

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Brand(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Shoe(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=50)
    size = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return f"{self.brand} - {self.name} - {self.color} - Size {self.size} - ${self.price}"

class Customer(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=250, null=True, blank=True)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.name
    
class Order(BaseModel):
    date_ordered = models.DateField()
    products = models.ManyToManyField(Shoe)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Order {self.id}"
    
class Comment(BaseModel):
    product = models.ForeignKey(Shoe, on_delete=models.CASCADE)
    author = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.IntegerField(null=True, default=0)

    def __str__(self):
        return f'{self.author} - {self.product}'
    

projectsite/Order/forms.py
from django import forms
from Order.models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'text', 'rating']
        

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
     

projectsite/Order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from Order.models import Shoe, Brand, Comment, Order, Customer
from Order.forms import CommentForm  
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse_lazy

def home(request):
    return render(request, 'home.html')

class BrandListView(ListView):
    model = Brand
    template_name = 'brand_list.html'
    context_object_name = 'brand'

class ShoeListView(ListView):
    model = Shoe
    template_name = 'shoe_list.html'
    context_object_name = 'shoes'
    paginate_by = 10

class ShoeDetailView(DetailView):
    model = Shoe
    template_name = 'shoe_detail.html'
    context_object_name = 'shoe'

class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'comment_form.html'

    def form_valid(self, form):
        form.instance.product = get_object_or_404(Shoe, id=self.kwargs['shoe_id'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('shoe-detail', kwargs={'pk': self.kwargs['shoe_id']})
        
class OrderListView(ListView):
    model = Order
    template_name = 'order_list.html'
    context_object_name = 'orders'

class OrderDetailView(DetailView):
    model = Order
    template_name = 'order_detail.html'
    context_object_name = 'order'

class CustomerListView(ListView):
    model = Customer
    template_name = 'customer_list.html'
    context_object_name = 'customers'

projectsite/Order/templates/base.html
<!-- base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Orderly</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-n2TXO5VJRRq4xnqMZtSEBkVfDNl6x5/oip6Q6DBGLj5ncNA8CDLNSvXYCFhcflVmSPBY8VJoZ6Qjp2No7vx0lg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

    <header>
        <h1q class="app-name">Order</h1>
        <!-- Add navigation links or other header content here -->
        <nav>
            <ul>
                <li><a href="{% url 'brand-list' %}">Brands</a></li>
                <li><a href="{% url 'shoe-list' %}">Shoes</a></li>
                <li><a href="{% url 'order-list' %}">Orders</a></li>
                <li><a href="{% url 'customer-list' %}">Customers</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    {% include 'footer.html' %}

</body>
</html>

projectsite/Order/templates/brand_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Categories</h2>
  <ul>
    {% for brands in brand %}
      <li>{{ brands.name }}</li>
    {% endfor %}
  </ul>
{% endblock %}

projectsite/Order/templates/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div id="form">
  <h2 id="title-form">Create a Comment</h2>
  <form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" id="submit">Submit</button>
  </form>
</div>
{% endblock %}

projectsite/Order/templates/customer_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Customers</h2>
  <ul>
    {% for customer in customers %}
      <li>{{ customer.name }} - Email: {{ customer.email }}</li>
    {% endfor %}
  </ul>
{% endblock %}

projectsite/Order/templates/footer.html
<footer>
    <br />
    <p>
      KICKZ<br />
      LIFE IS TOO BORING WITH BAD SHOES
    </p>
    <br>
    <div class="social-icons">
      <a href="https://github.com/Agz-23" target="_blank" class="icon-link">
        <i class="fab fa-github"></i>
      </a>
      <a href="https://www.facebook.com/lenor.montierro/" target="_blank" class="icon-link">
        <i class="fab fa-facebook"></i>
      </a>
      <a href="https://www.instagram.com/lenor.montierro/" target="_blank" class="icon-link">
        <i class="fab fa-instagram"></i>
      </a>
      <!-- Add other social media icons similarly -->
    </div>
    <p>
      &copy; 2023 KICKZ. All Rights Reserved.
    </p>
  </footer>

projectsite/Order/templates/home.html
<!-- home.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>Welcome to the Kickz</h2>
 
{% endblock %}

projectsite/Order/templates/order_detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>Order #{{ order.id }}</h2>

  <h3>Order Details</h3>
  <p>Date Ordered: {{ order.date_ordered }}</p>
  <p>Total Amount: ${{ order.total_amount }}</p>


  <h3>Products</h3>
<ul>
  {% if order.orderitem_set.all %}
    {% for item in order.orderitem_set.all %}
      <li>{{ item.product.name }} - Quantity: {{ item.quantity }} - Price: ${{ item.product.price }}</li>
    {% endfor %}
  {% else %}
    <li>No items in the order</li>
  {% endif %}
</ul>
{% endblock %}

projectsite/Order/templates/order_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Orders</h2>
  <ul>
    {% for order in orders %}
      <li><a href="{% url 'order-detail' pk=order.pk %}">Order #{{ order.id }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

projectsite/Order/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if objects.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ objects.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ objects.number }} of {{ objects.paginator.num_pages }}.
        </span>

        {% if objects.has_next %}
            <a href="?page={{ objects.next_page_number }}">next</a>
            <a href="?page={{ objects.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

projectsite/Order/templates/shoe_detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>{{ shoe.name }}</h2>
  
  <p>{{ shoe.description }}</p>
  

  <img src="{{ shoe.image.url }}" alt="{{ shoe.name }}" width="200">

 
  <p>Price: ${{ shoe.price }}</p>

  <h3>Comments</h3>
  {% for review in shoe.comment_set.all %}
    <p>{{ review.text }} - {{ review.author }} ({{ review.created_at }})</p>
  {% empty %}
    <p>No comment yet.</p>
  {% endfor %}

  <a href="{% url 'comment-create' product_id=shoe.pk %}">Add Comment</a>
{% endblock %}

projectsite/Order/templates/shoe_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Shoes</h2>
  <ul>
    {% for shoe in shoes %}
      <li><a href="{% url 'shoe-detail' pk=shoe.pk %}">{{ shoe.name }}</a></li>
    {% endfor %}
  </ul>

 
  <div class="pagination">
    <span class="step-links">
      {% if shoe.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ shoe.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ shoe.number }} of {{ shoe.paginator.num_pages }}.
      </span>

      {% if shoe.has_next %}
        <a href="?page={{ shoe.next_page_number }}">next</a>
        <a href="?page={{ shoe.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
{% endblock %}